version: "3"

services:
  rabbitmq_service:
    image: "rabbitmq:3-management"
    container_name: rabbitmq_service

    hostname: "rmq-host"

    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "pass"

    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 15s
      retries: 5

    ports:
      - "5672:5672"
      - "15672:15672"

    privileged: true

    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.3

    networks:
      - appnet

  energy-unit-service:
    build:
      context: ./energy_unit_service
      dockerfile: Dockerfile

    restart: on-failure

    volumes:
      - ./energy_unit_service:/app

    working_dir: /app
    command: make run
    ports:
      - "4040:4040"

    depends_on:
      rabbitmq_service:
        condition: service_healthy

    privileged: true

    networks:
      - appnet

  scenariste-service:
    build:
      context: ./scenarist_service
      dockerfile: Dockerfile

    restart: on-failure

    volumes:
      - ./scenarist_service:/app

    working_dir: /app
    command: make run
    ports:
      - "2024:2024"

    depends_on:
      rabbitmq_service:
        condition: service_healthy
      energy-unit-service:
        condition: service_started

    privileged: true

    networks:
      - appnet

networks:
  appnet:
    driver: bridge
